### DISCUSSION TITLE
CSS-IN-JS : React 인기 CSS 방식

### DISCUSSION THREAD

**Discussion by seonae-j** [seonae-j/TIL#88] [React]
### CSS-IN-JS
- CSS 를 js 안에 넣어서 만들겠다는 의미

**[기존 CSS 방식]**
```css
.title {
  width: 996px;
  height: 52px;
}
```

**[CSS-IN-JS 방식]**
```javascript
const Title = styled.div`
  width: 996px;
  height: 52px;
`
``` 

- js 변수에다 css, js, html 코드가 다 합쳐진 태그를 만드는 것이다.
